#ifndef LP_PLUGIN_SINGA_KNITTING_GLOBAL_H
#define LP_PLUGIN_SINGA_KNITTING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LP_PLUGIN_SINGA_KNITTING_LIBRARY)
#  define LP_PLUGIN_SINGA_KNITTING_EXPORT Q_DECL_EXPORT
#else
#  define LP_PLUGIN_SINGA_KNITTING_EXPORT Q_DECL_IMPORT
#endif

#endif // LP_PLUGIN_SINGA_KNITTING_GLOBAL_H
